### ISSUE TITLE
There is a problem with blend deinterlacing in post processes.

### ISSUE THREAD

**Issue by mizumanju** [pinterf/TIVTC#1]
Blend deinterlacing of PP = 2 and 5, frames will become a mess. Please refer to the image of the following URL.
http://i.imgur.com/LprKo5Z.jpg

LWLibavVideoSource("source.ts",dr =true).CropBottom(1008)
TFMstacker(opt=3)
Overlay(version(),60)
return last     #
function TFMstacker(clip last, int "opt"){
c0=TFM(PP=0,opt=opt,MI=0).subtitle("PP=0").subtitle("opt="+String(opt),y=20)
c1=TFM(PP=1,opt=opt,MI=0).subtitle("PP=1").subtitle("opt="+String(opt),y=20)
c2=TFM(PP=2,opt=opt,MI=0).subtitle("PP=2").subtitle("opt="+String(opt),y=20)
c3=TFM(PP=3,opt=opt,MI=0).subtitle("PP=3").subtitle("opt="+String(opt),y=20)
c4=TFM(PP=4,opt=opt,MI=0).subtitle("PP=4").subtitle("opt="+String(opt),y=20)
c5=TFM(PP=5,opt=opt,MI=0).subtitle("PP=5").subtitle("opt="+String(opt),y=20)
c6=TFM(PP=6,opt=opt,MI=0).subtitle("PP=6").subtitle("opt="+String(opt),y=20)
c7=TFM(PP=7,opt=opt,MI=0).subtitle("PP=7").subtitle("opt="+String(opt),y=20)
return StackVertical(c0,c1,c2,c3,c4,c5,c6,c7)}

**Comment by pinterf** [comment]
Thanks for the report, fixed

**Comment by mizumanju** [comment]
Thank you for quick response.
