### ISSUE TITLE
TDeInt v1.4 made green border

### ISSUE THREAD

**Issue by hintlou** [pinterf/TIVTC#10]
After I updated to TDeInt v1.4,it made green borders.
my code: TDeint(mode=2,type=2,slow=2,order=-1)
![陶喆 就是爱你 - 2527](https://user-images.githubusercontent.com/53346325/81819146-82614300-9561-11ea-9337-d9e33c063eec.png)

**Comment by pinterf** [comment]
Thanks for the report, check TDeint 1.5 please.

**Comment by pinterf** [comment]
Fixed in https://github.com/pinterf/TIVTC/commit/a03356956bd3c06112d68db456c4cfa65ddef271
