### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by Yohan050** [pinterf/TIVTC#11]
Hi  pinterf,

I tried to made a  VFR encode in 2 pass.  No problem in the pass one, but on the pass 2, avisynth says I has access violation. It's the first time i has that.  I made many VFR encode in the past, I never his any errors. I tried with your last release and the old version of TIVTC (1.0.5), the error is same.

Can you check where this error is coming from? Thanks you for advance.

https://puu.sh/FNncc.png

**Comment by pinterf** [comment]
What video format are you using? Could you test it with a ConvertToYuy2 after the source filter? I found issues since the release at yv16 inputs.

**Comment by Yohan050** [comment]
My source is on 8 bits, that is this mediainfo : https://puu.sh/FNnVu.txt
It work with ConvertToYuy2. Thanks you very much.

**Comment by pinterf** [comment]
Thanks. It's YV12. Then it's an unknown issue unless it got fixed since v17 with the huge code cleanups.

**Comment by Yohan050** [comment]
I will add an extra information.  I found my old script and I retested with the video and no problem. The issue same came form vfrDec=1.
Old script : 
Pass 1
TFM(mode=1,output="tfm.txt")
TDecimate(mode=4,output="stats.txt")
Pass 2
TFM(mode=1)
TDecimate(mode=5,hybrid=2,dupthresh=1.0,input="stats.txt",tfmin="tfm.txt",mkvout="timecodes.txt")

New script : 
Pass 1
tfm(output="matches.txt")
tdecimate(mode=4,output="metrics.txt")
Pass 2
tfm(input="matches.txt")
tdecimate(mode=5,hybrid=2,vfrDec=1,input="metrics.txt",tfmIn="matches.txt",mkvOut="mkv-timecodesfile.txt")
This one came from the official exemple of Avisynth.

I hope it can guide you a little more to fix the bug.

**Comment by pinterf** [comment]
Thanks, but could not reproduce. Maybe it depends on the source video content?
Q1: Could you upload a test sample which still produces the error (size is no limit on my side).
Q2: I was trying with avsmeter64, and virtualdub2. I wonder if they produce the same error for you?

**Comment by Yohan050** [comment]
A1: https://mega.nz/file/hw8EWCSQ#6C86hHjhTop_f4Vc6sp2tjV_IzJdbZomX0BN_X4NgV8 Here is the file you requested.
A2:  Sound work with avsmeter and virtualdub. https://puu.sh/FNvKF.png https://puu.sh/FNvPq.png

**Comment by pinterf** [comment]
Thanks, now I can see that you are using avs 2.6. Are you using Crop somewhere in your script?

**Comment by Yohan050** [comment]
No, I plan to add one but in the basic version, there is only LwlibavVideosource, TFM and Tdecimate, like my first screen. I will copy my scripts.

Pass1.avs
`LWLibavVideoSource(source="00006.m2ts", repeat=True)

tfm(output="matches.txt")
tdecimate(mode=4,output="metrics.txt")`

Pass2.avs
`LWLibavVideoSource(source="00006.m2ts", repeat=True)

tfm(input="matches.txt")
tdecimate(mode=5,hybrid=2,vfrDec=1,input="metrics.txt",tfmIn="matches.txt",mkvOut="mkv-timecodesfile.txt")`

**Comment by pinterf** [comment]
Knowing that you are trying with avs 2.6 32 bit helped a lot. Strange, it was not 32 bit specific.
Could you please try this build: 
https://drive.google.com/open?id=1kUsTcYXtQHE7F2wrasDp8xivUFIQws0q

**Comment by Yohan050** [comment]
It work.
