### ISSUE TITLE
Crashes in v1.0.19

### ISSUE THREAD

**Issue by microace** [pinterf/TIVTC#12]
The following script crashes in latest Avisynth+ x64 using TIVTC v1.0.19
`mpeg2source("rule6.d2v")`
`TFM(pp=1,display=true)`

Was able to reproduce:
- in Virtualdub2, Avspmod, avsmeter, ffmpeg and x264
- when OSD is enabled (display=true) AND,
- when postprocessing is set to mode 1 (PP=1)
- with multiple sources
- using multiple source filters (LSMASHSource, ffms2 and mpegdecplus)
- with autoloading disabled and enabled

Was not able to reproduce:
- with TIVTC v1.0.17
- when OSD disabled (display=false) OR,
- when postprocessing is disabled or set to mode >1 

The crashes also only seem to occur (or at least easier to reproduce) on sources that need postprocessing. Bug can also be pretty easily reproduced on any source by setting the MI parameter very low to force TFM to detect lots of frames as combed.

**Comment by pinterf** [comment]
Thanks for the report, pls check v1.0.20

**Comment by pinterf** [comment]
Fixed in https://github.com/pinterf/TIVTC/commit/1693a161ebc6568c4f55337988dcfca81313af71
