### ISSUE TITLE
d.blockx may not be set

### ISSUE THREAD

**Issue by 299792458m** [pinterf/TIVTC#13]
aren't they to set blockx?
https://github.com/pinterf/TIVTC/blob/0464aa7a98faf9967d830b0b52f1d0176aa0042a/src/TIVTC/FrameDiff.cpp#L364
https://github.com/pinterf/TIVTC/blob/0464aa7a98faf9967d830b0b52f1d0176aa0042a/src/TIVTC/TDecimate.cpp#L1006
https://github.com/pinterf/TIVTC/blob/0464aa7a98faf9967d830b0b52f1d0176aa0042a/src/TIVTC/TDecimate.cpp#L1146

**Comment by pinterf** [comment]
Of course it's wrong! Thanks for pointing out on that! I'm not at my PC, which modes did it affect?

**Comment by pinterf** [comment]
Fixed in v1.0.21

**Comment by 299792458m** [comment]
thanks.
I noticed because the calcDiff_SADorSSD_32x32_SSE2 function wasn't used.

But if I fixed that blockx, the result become changed. So, I confused what was right..
and find that with subsampling!=0, something need to be changed , so 32x32 function may be as same form as generic function.(x/yshifta or x/yhalfa to be used?).
https://github.com/pinterf/TIVTC/blob/ca38bab0afc044aadf6670a1f551b50395dfb641/src/TIVTC/TDecimateASM.cpp#L1084
https://github.com/pinterf/TIVTC/blob/ca38bab0afc044aadf6670a1f551b50395dfb641/src/TIVTC/TDecimateASM.cpp#L1094
and maybe jist typo xsubsampling == 2?
https://github.com/pinterf/TIVTC/blob/ca38bab0afc044aadf6670a1f551b50395dfb641/src/TIVTC/TDecimateASM.cpp#L1095

**Comment by pinterf** [comment]
YV411: Yep, another good catch, thanks. Fixed. (I'm not making a release from that yet).

**Comment by 299792458m** [comment]
I found why result was changed when Using calcDiff_SADorSSD_32x32_SSE2.
These lines is not needed...
https://github.com/pinterf/TIVTC/blob/7f216e76c2bcecbf78836d6ad880edf951285c2f/src/TIVTC/TDecimateASM.cpp#L326
https://github.com/pinterf/TIVTC/blob/7f216e76c2bcecbf78836d6ad880edf951285c2f/src/TIVTC/TDecimateASM.cpp#L327

**Comment by pinterf** [comment]
Thank you, I'll incorporate them soon and this one really deserves a fixed release.

**Comment by 299792458m** [comment]
Thanks!

**Comment by pinterf** [comment]
Thanks for the contribution, I hope not much other bugs left after the huge code reorganizations.
