### ISSUE TITLE
TDeint HBD emask

### ISSUE THREAD

**Issue by realfinder** [pinterf/TIVTC#15]
hi

Asd has ported vsTMM with HBD, but seems TDeint emask only work with 8bit for now https://github.com/Asd-g/AviSynth-vsTMM/issues/1

**Comment by pinterf** [comment]
As noted in
https://github.com/pinterf/TIVTC/blob/master/Doc_TDeint/tdeint.htm#L647
mask clip has nothing to do with high bit depth.
It contains special byte values (10, 20, ..) which are bit depth independent I think.

**Comment by Asd-g** [comment]
I changed back the values so they are 10/20....60 for any bit depth.
Now high bit depth support for emask (also for internal mask?) could be added?

**Comment by pinterf** [comment]
Note that I have never used these plugins for myself and I am not familiar with them, so you have to enlighten me about the use cases and test scenarios on possible emask usage and generation. In my mind this mask is a special purpose marker clip (like e.g. motion vector clip in mvtools) which has zero benefit of being twice (16 bits) or four times (possible float) larger than necessary.

**Comment by realfinder** [comment]
"enlighten me about the use cases and test scenarios on possible emask usage and generation"
this one may help https://github.com/Asd-g/AviSynth-vsTMM/issues/2#issuecomment-670043221

**Comment by pinterf** [comment]
I have already seen that but I still don't understand the reason. I had a look at the internal mask operations and I'm sure that internal the mask handling must stay with the existing 8 bits. Mask's sole purpose is holding a finite number of distinct values (10, 20, 30, 40, 50, 60, 70 and 255). I'd say it's easier to call a ConvertBits(8) right in the constructor than handle this special clip in 16 bits internally as well.

I admit that the modification would be only a nuance compared to the code changes I made so far but I don't see its meaningfulness.

**Comment by realfinder** [comment]
ConvertBits(8) wont work with the last change Asd did, and is it ok in the first place?

maybe with the older vstmm it's easy to just take the 1st byte regardless the bits (but this will not work with float clip I think)

and if I was right about the float case then vstmm need to provides 8bit mask

**Comment by realfinder** [comment]
> 
> 
> I have already seen that but I still don't understand the reason.

the reason is that Asd see it's better when the entire chain works in same bit depth https://github.com/Asd-g/AviSynth-vsTMM/issues/2#issuecomment-670058265

**Comment by Asd-g** [comment]
I'm in the same boat - I'm not using these filters (I'm filtering mainly progressive video).
Test:
```
ConvertBits(16)
tdeint(emask=vstmm().ConvertBits(8))
ConvertBits(8)
```
The output is - https://images2.imgbox.com/f6/c3/eps8aaWV_o.png (1)
```
ConvertBits(16)
tdeint(emask=ConvertBits(8).vstmm())
ConvertBits(8)
```
The output is - https://images2.imgbox.com/ed/46/GW1YwEBl_o.png (2)
Unfiltered image - https://images2.imgbox.com/66/d2/xVEa46gO_o.png
The difference - (1) https://images2.imgbox.com/a4/da/42fX1INg_o.png and (2) https://images2.imgbox.com/b8/8b/95Ftr5os_o.png
Sample - https://gofile.io/d/9zcYLl The images are from frame 168.
It seems high bit depth is helping for better decision what pixel is static or moving?
However, yes, there is no benefit if the entire chain works in the same bit depth. I just think is more intuitive when everything is in same bit depth (no speed penalty here?).
I'll add option to vstmm for always 8-bit output. This ticket could be closed.

**Comment by realfinder** [comment]
I will close it then
