### ISSUE TITLE
edeint bug with HBD

### ISSUE THREAD

**Issue by realfinder** [pinterf/TIVTC#17]
with

```
ColorBars(width=720, height=480, pixel_type="yv12")
ConvertBits(16)
tdeint(edeint=nnedi3)
ConvertBits(8)
```
at least with x64 I got this
![image](https://user-images.githubusercontent.com/2512153/93692123-d70c6000-faf7-11ea-90d1-f3d1ef1ec517.png)

**Comment by realfinder** [comment]
maybe it same as https://github.com/pinterf/TIVTC/issues/16

**Comment by pinterf** [comment]
Reproduced, bug found, tests on the way

**Comment by pinterf** [comment]
Could you try this build, if it is O.K. then I release.
https://docs.google.com/uc?export=download&id=160rQ59OZPfi39T8dg48pGMm1H5Ia3dfS

**Comment by realfinder** [comment]
that seems work. thanks
