### ISSUE TITLE
TDecimate::fullInfo is always false

### ISSUE THREAD

**Issue by dubhater** [pinterf/TIVTC#22]
Hi!

I noticed that TDecimate::fullInfo is always false, which means that rerunFromStart never runs. Is that on purpose?

**Comment by pinterf** [comment]
Definitely not. I found the original lines, now I investigate when and why it disappeared.

**Comment by pinterf** [comment]
Partially undefined in 91c55b89 then removed in 5ed00e70.

**Comment by pinterf** [comment]
Thanks for the report, fixed in a3d1354b

**Comment by dubhater** [comment]
Thanks for the quick fix!
