### ISSUE TITLE
TDeint 1.8 crashes with AviSynth 2.6.0

### ISSUE THREAD

**Issue by the-real-akapuma** [pinterf/TIVTC#29]
I have a movie with a resolution of 720x576 pixels. I have the following AVS script (hash not in quotes):

_mpeg2source("K:\Recorder\aaa\aaa.d2v")
"#" crop(2,2,696,572)
TDeint()_

- I can open and play it with GordianKnot
- I can open and play it with the MPC-HC
- I can open and play it with the MSU VQMT
- I can process it with AVSMeter 3.0.9.0

This works with TDeint 1.1 (latest version of tritical) as well as with TDeint 1.8 (20201214, latest version of pinterf).
It works with AviSynth 2.6.0.5 and AviSynth+ 3.7.0.

If I now remove the hash before the crop, it still works fine with TDeint 1.1 and with TDeint 1.8, when AviSynth+ is used.
It still works fine with TDeint 1.1 when AviSynth 2.6.0 is used.

But with TDeint 1.8 and AviSynth 2.6.0, it no longer works.

GordianKnot and MSU VQMT show the following:
Avisynth: access violation at 0x000032A0 in C:\Program Files\ AviSynth 2.5\plugins\TDeint.dll, attemting to read from 0xFFFFFF.

The MPC-HC crashes completely:
WARNING: Following frames may be wrong.
tdeint!Ordinal0+0x32a0
tdeint!Ordinal0+0x7355

AVSMeter 3.0.9.0 shows:
Exception 0xC0000005 [STATUS_ACCESS_VIOLATION]
Module:   C:\test\TDeint.dll
Address:  0x6D8932A0

Tested on Win7 and WIn10.

Best regards

akapuma

**Comment by pinterf** [comment]
Avisynth 2.6 makes an 'unaligned' crop by default which is not recommended since it breaks the assumption that all frame buffer data begins at 16 bytes aligned memory address.
So please add align=true parameter to Crop when using Avisynth 2.6

**Comment by the-real-akapuma** [comment]
Thank you very much.

Best regards

akapuma
