### ISSUE TITLE
x64 version is broken

### ISSUE THREAD

**Issue by DJATOM** [pinterf/TIVTC#3]
TFM can't find combed frames in x64 mode. Test script:

> MPEG2Source("test.d2v") # Any DVD Video 
> tfm(pp=1,output="01.txt")

It was triggered by my friend but he can't speak English, that's why I'm reporting it.

**Comment by pinterf** [comment]
I could not reproduce, though it was run through with another source.
TIVTC 1.09 x86 and x64 and original 1.05 (x86) gave me identical results.
What does "broken" mean? It suddenly went wrong in 1.09 x64?
What happens when he is running the script with 1.05 or 1.09 x86?
Thanks.

**Comment by DJATOM** [comment]
Hmm, it seems my avs2yuv64 is the culprit. Analyse pass went ok with avs2avi64 :D
