### ISSUE TITLE
TFM 1.0.27 not detecting field order?

### ISSUE THREAD

**Issue by flossy83** [pinterf/TIVTC#41]
There may be an issue with TFM not detecting the field order properly in v1.0.27.

The order=-1 parameter is supposed to auto detect the field order from Avisynth. 

From my end it seems like v1.0.26 correctly detects the field order on a per-frame basis, but perhaps v1.0.27 does not?

For debugging convenience you can force a field order change per-frame with this:

```
DoubleWeave()  # alternates the field order per-frame
ScriptClip("""SubTitle(String(GetParity(current_frame)))""")
```

The subtitle should alternate between true/false every frame, and TFM v1.0.27 should see this internally (I suspect it's just interpreting all frames as either TFF or BFF).

**I could be wrong**, but if my hypothesis is true it would explain why I am seeing a failure to fieldmatch in 1.0.27 but not in 1.0.26, for source clips whose field order changes on a per-frame basis. 

Thank you

**Comment by realfinder** [comment]
can you post a simple clip and script so pinterf can test easily?

**Comment by flossy83** [comment]
Sorry should have done that first.

Test clip (DVD remux, 480i, 3:2 hard telecine, all frames TFF)
https://drive.google.com/file/d/1_0uzhTMfqthTqtRUV78hrzY7ncgdhgX5/view?usp=sharing


```
LWLibavVideoSource("C:\tfm_test.mkv", repeat=true)
DoubleWeave()  # results in alternating field order
TFM(mode=0, PP=0, display=true) 
```

Results:


v1.0.26 (order alternates between 0 and 1, as it should)
![TFM v1026](https://github.com/pinterf/TIVTC/assets/46382337/33ff9a62-7468-4bc7-823b-7483b1875a6f)

v1.0.27 (order stays fixed at 1; failure to field match many frames)
![TFM v1027](https://github.com/pinterf/TIVTC/assets/46382337/eb001d34-6674-4090-91d2-6df4e035b0c0)

**Comment by flossy83** [comment]
Curiously, if I use colorbars instead of real clip like so...

```
ColorBars(pixel_type="YV12").KillAudio()
DoubleWeave()   # results in alternating field order - TFM should see it
TFM(order=-1, mode=0, PP=0, display=true)
```

...then TFM's "order" DOES alternate between 0 and 1 (as it should)

But with the real world clip it doesn't - strange.

**Comment by realfinder** [comment]
ok, I test and see, the problem with DoubleWeave() and frame properties, since tfm will use _FieldBased instead of classic "field order" (GetParity) if there are _FieldBased prop, so I think it's avs+ DoubleWeave() problem not tivtc

DoubleWeave().propDelete("_FieldBased") should fix it for now until @pinterf say the final word

**Comment by flossy83** [comment]
I can confirm that deleting _FieldBased resolves the issue - thanks.

[BWDIF also preferences _FieldBased over Avisynth order ](https://github.com/Asd-g/AviSynth-BWDIF/issues/6), so I should have checked for that, but it just didn't occur to me.   

Probably because I am in the mindset that frame properties are like these helpful bits of extra metadata that we add to the clip, so I don't expect them to result in broken output but just providing extra information that could be useful.

There are scenarios where I do want to preference _FieldBased over AVS field order, but then it will cause wrong behaviour with some AVS internal functions and possibly some third party ones so I don't really know what is optimal.

**Comment by pinterf** [comment]
This dual behaviour - Avisynth's VideoInfo flag vs. frame properties - must somehow be resolved. Frame properties were introduced much later (originally from VapourSynth) and are only used by plugins. Logically, it would be nice that Avisynth handles the new frame property based method as well, and support in all its relevant internal filters and functions. The priority of the flags (first: frame property, then if it does not exist: from video info) must clearly be defined. Still, present IsFieldBased, IsFrameBased are using flags from the static VideoInfo structure (which remains the same throughout the clip's lifetime); this is a much cleaner and more optimal function. At a frame property based solution IsFieldBased and IsFrameBased must be evaluated at each frame, though their results are the same for all frames in the clip. GetParity is already evaluated for all frames, its result relies on the frame number now. So ideally, in the future, Avisynth must handle frame properties and old-style flags as well, keeping them in synchron.

**Comment by flossy83** [comment]
Yes, I suppose for backwards compatibility it would be nice if Avisynth's internal functions like DoubleWeave would automatically set the frame properties as well, given that popular plugins like TFM and BWDIF are now preferencing those properties.

But there are still other filters like [NNEDI3 which only supports static field order](https://github.com/jpsdr/NNEDI3/issues/12).  So for now I'm always using LwLibAV with repeat=true to convert NTSC DVDs to fixed field order 30i.

I can't recall seeing any PAL DVDs which had dynamic field order, just one of my PVR recordings of 576i from TV broadcast had a field order change a few seconds after playback but I think it was due to splicing the clip.
