### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by flossy83** [pinterf/TIVTC#44]
I'm trying to make a small tweak/fix to TDecimate's hybrid=3 mode (details [here](https://forum.doom9.org/showthread.php?p=1996299#post1996299)) and have managed to set up the whole MSys2/Mingw64 environment just now for the first time.

The first of the two build commands seems ok:
```
# cmake .. -G "MinGW Makefiles" -DENABLE_INTEL_SIMD:bool=on
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected target processor as: AMD64
../common/TCommonASM.cpp;../common/TCommonASM.h;../common/fixedfonts.cpp;../common/fixedfonts.h;../common/info.cpp;../common/info.h;../common/internal.cpp;../common/internal.h;../include/avisynth.h;../include/avs/alignment.h;../include/avs/capi.h;../include/avs/config.h;../include/avs/cpuid.h;../include/avs/filesystem.h;../include/avs/minmax.h;../include/avs/posix.h;../include/avs/types.h;../include/avs/win.h;Cache.cpp;Cache.h;Cycle.cpp;Cycle.h;FieldDiff.cpp;FieldDiff.h;Font.h;FrameDiff.cpp;FrameDiff.h;IsCombedTIVTC.cpp;MergeHints.cpp;MergeHints.h;PlanarFrame.cpp;PlanarFrame.h;PluginInit.cpp;RequestLinear.cpp;RequestLinear.h;TDecimate.cpp;TDecimate.h;TDecimateASM.cpp;TDecimateASM.h;TDecimateBlur.cpp;TDecimateMode2.cpp;TDecimateMode7.cpp;TDecimateOut.cpp;TFM.cpp;TFM.h;TFMASM.cpp;TFMD2V.cpp;TFMPP.cpp;TFMPP.h;TFMPlanar.cpp;TFMYUY2.cpp;TFMasm.h;calcCRC.cpp;calcCRC.h;profUtil.cpp;profUtil.h;resource.h
../common/TCommonASM.cpp;../common/TCommonASM.h;../common/fixedfonts.cpp;../common/fixedfonts.h;../common/info.cpp;../common/info.h;../common/internal.cpp;../common/internal.h;../include/avisynth.h;../include/avs/alignment.h;../include/avs/capi.h;../include/avs/config.h;../include/avs/cpuid.h;../include/avs/filesystem.h;../include/avs/minmax.h;../include/avs/posix.h;../include/avs/types.h;../include/avs/win.h;TDBuf.cpp;TDBuf.h;TDeintASM.cpp;TDeintASM.h;TDeinterlace.cpp;TDeinterlace.h;TDeinterlacePlanar.cpp;TDeinterlaceYUY2.cpp;THelper.cpp;THelper.h;TSwitch.cpp;TSwitch.h;resource.h
-- Configuring done
-- Generating done
-- Build files have been written to: C:/TIVTC-master/src/TIVTC
```

But the second command fails:

```
# cmake --build . --config Release
[  2%] Building CXX object TIVTC/CMakeFiles/TIVTC.dir/__/common/TCommonASM.cpp.obj
[  5%] Building CXX object TIVTC/CMakeFiles/TIVTC.dir/__/common/fixedfonts.cpp.obj
[  7%] Building CXX object TIVTC/CMakeFiles/TIVTC.dir/__/common/info.cpp.obj
In file included from C:\TIVTC-master\src\common\info.cpp:27:
C:/TIVTC-master/src/include/avs/win.h:44: warning: "STRICT" redefined
   44 | #define STRICT
      |
In file included from C:/msys64/mingw64/include/windef.h:9,
                 from C:/msys64/mingw64/include/windows.h:69,
                 from C:\TIVTC-master\src\common\internal.h:12,
                 from C:\TIVTC-master\src\common\info.h:30,
                 from C:\TIVTC-master\src\common\info.cpp:23:
C:/msys64/mingw64/include/minwindef.h:11: note: this is the location of the previous definition
   11 | #define STRICT 1
      |
C:\TIVTC-master\src\common\info.h:74:6: error: 'unique_ptr' in namespace 'std' does not name a template type
   74 | std::unique_ptr<BitmapFont> GetBitmapFont(int size, const char* name, bool bold, bool debugSave);
      |      ^~~~~~~~~~
C:\TIVTC-master\src\common\info.h:35:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   34 | #include <vector>
  +++ |+#include <memory>
   35 |
C:\TIVTC-master\src\common\info.cpp:46:13: error: 'unique_ptr' in namespace 'std' does not name a template type
   46 | static std::unique_ptr<wchar_t[]> AnsiToWideCharACP(const char* s_ansi)
      |             ^~~~~~~~~~
C:\TIVTC-master\src\common\info.cpp:44:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   43 | #include "fixedfonts.h"
  +++ |+#include <memory>
   44 |
C:\TIVTC-master\src\common\info.cpp:55:13: error: 'unique_ptr' in namespace 'std' does not name a template type
   55 | static std::unique_ptr<wchar_t[]> Utf8ToWideChar(const char* s_ansi)
      |             ^~~~~~~~~~
C:\TIVTC-master\src\common\info.cpp:55:8: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   55 | static std::unique_ptr<wchar_t[]> Utf8ToWideChar(const char* s_ansi)
      |        ^~~
C:\TIVTC-master\src\common\info.cpp: In function 'std::wstring charToWstring(const char*, bool)':
C:\TIVTC-master\src\common\info.cpp:110:20: error: 'AnsiToWideCharACP' was not declared in this scope
  110 |     auto wsource = AnsiToWideCharACP(text);
      |                    ^~~~~~~~~~~~~~~~~
C:\TIVTC-master\src\common\info.cpp: At global scope:
C:\TIVTC-master\src\common\info.cpp:906:6: error: 'unique_ptr' in namespace 'std' does not name a template type
  906 | std::unique_ptr<BitmapFont> GetBitmapFont(int size, const char *name, bool bold, bool debugSave) {
      |      ^~~~~~~~~~
C:\TIVTC-master\src\common\info.cpp:906:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
  906 | std::unique_ptr<BitmapFont> GetBitmapFont(int size, const char *name, bool bold, bool debugSave) {
      | ^~~
C:\TIVTC-master\src\common\info.cpp: In function 'void DrawStringPlanar(VideoInfo&, PVideoFrame&, int, int, const char*)':
C:\TIVTC-master\src\common\info.cpp:1142:8: error: 'unique_ptr' is not a member of 'std'
 1142 |   std::unique_ptr<BitmapFont> current_font = GetBitmapFont(20, "info_h", false, false); // 10x20
      |        ^~~~~~~~~~
C:\TIVTC-master\src\common\info.cpp:1142:8: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
C:\TIVTC-master\src\common\info.cpp:1142:29: error: expected primary-expression before '>' token
 1142 |   std::unique_ptr<BitmapFont> current_font = GetBitmapFont(20, "info_h", false, false); // 10x20
      |                             ^
C:\TIVTC-master\src\common\info.cpp:1142:31: error: 'current_font' was not declared in this scope
 1142 |   std::unique_ptr<BitmapFont> current_font = GetBitmapFont(20, "info_h", false, false); // 10x20
      |                               ^~~~~~~~~~~~
C:\TIVTC-master\src\common\info.cpp:1142:46: error: 'GetBitmapFont' was not declared in this scope; did you mean 'BitmapFont'?
 1142 |   std::unique_ptr<BitmapFont> current_font = GetBitmapFont(20, "info_h", false, false); // 10x20
      |                                              ^~~~~~~~~~~~~
      |                                              BitmapFont
mingw32-make[2]: *** [TIVTC\CMakeFiles\TIVTC.dir\build.make:106: TIVTC/CMakeFiles/TIVTC.dir/__/common/info.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:142: TIVTC/CMakeFiles/TIVTC.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2
```

The only thing that stands out to me is the last 3 lines "mingw32-make" - shouldn't that be mingw64?

Here are my installed MinGW packages btw:

```
mingw-w64-ucrt-x86_64-binutils 2.39-2
mingw-w64-ucrt-x86_64-crt-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-ucrt-x86_64-gcc 12.2.0-4
mingw-w64-ucrt-x86_64-gcc-libs 12.2.0-4
mingw-w64-ucrt-x86_64-gcc-objc 12.2.0-4
mingw-w64-ucrt-x86_64-gmp 6.2.1-3
mingw-w64-ucrt-x86_64-headers-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-ucrt-x86_64-isl 0.25-1
mingw-w64-ucrt-x86_64-libgccjit 12.2.0-4
mingw-w64-ucrt-x86_64-libiconv 1.17-1
mingw-w64-ucrt-x86_64-libwinpthread-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-ucrt-x86_64-mpc 1.2.1-1
mingw-w64-ucrt-x86_64-mpfr 4.1.0.p13-1
mingw-w64-ucrt-x86_64-windows-default-manifest 6.4-4
mingw-w64-ucrt-x86_64-winpthreads-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-ucrt-x86_64-zlib 1.2.13-1
mingw-w64-ucrt-x86_64-zstd 1.5.2-2
mingw-w64-x86_64-binutils 2.39-2
mingw-w64-x86_64-brotli 1.0.9-5
mingw-w64-x86_64-bzip2 1.0.8-2
mingw-w64-x86_64-c-ares 1.18.1-1
mingw-w64-x86_64-ca-certificates 20211016-3
mingw-w64-x86_64-cmake 3.24.2-4
mingw-w64-x86_64-crt-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-x86_64-curl 7.86.0-2
mingw-w64-x86_64-expat 2.4.9-1
mingw-w64-x86_64-gcc 12.2.0-4
mingw-w64-x86_64-gcc-libs 12.2.0-4
mingw-w64-x86_64-gcc-objc 12.2.0-4
mingw-w64-x86_64-gettext 0.21-3
mingw-w64-x86_64-gmp 6.2.1-3
mingw-w64-x86_64-headers-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-x86_64-isl 0.25-1
mingw-w64-x86_64-jansson 2.14-2
mingw-w64-x86_64-jemalloc 5.3.0-1
mingw-w64-x86_64-jsoncpp 1.9.5-1
mingw-w64-x86_64-libarchive 3.6.1-2
mingw-w64-x86_64-libb2 0.98.1-2
mingw-w64-x86_64-libffi 3.4.3-1
mingw-w64-x86_64-libgccjit 12.2.0-4
mingw-w64-x86_64-libiconv 1.17-1
mingw-w64-x86_64-libidn2 2.3.3-1
mingw-w64-x86_64-libpsl 0.21.1-4
mingw-w64-x86_64-libssh2 1.10.0-1
mingw-w64-x86_64-libsystre 1.0.1-4
mingw-w64-x86_64-libtasn1 4.19.0-1
mingw-w64-x86_64-libtre-git r128.6fb7206-2
mingw-w64-x86_64-libunistring 1.0-1
mingw-w64-x86_64-libuv 1.44.2-1
mingw-w64-x86_64-libwinpthread-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-x86_64-libxml2 2.10.3-1
mingw-w64-x86_64-lz4 1.9.4-1
mingw-w64-x86_64-make 4.3-1
mingw-w64-x86_64-mpc 1.2.1-1
mingw-w64-x86_64-mpfr 4.1.0.p13-1
mingw-w64-x86_64-nghttp2 1.50.0-1
mingw-w64-x86_64-ninja 1.11.1-2
mingw-w64-x86_64-openssl 1.1.1.q-1
mingw-w64-x86_64-p11-kit 0.24.1-3
mingw-w64-x86_64-pkgconf 1~1.8.0-2
mingw-w64-x86_64-rhash 1.4.3-1
mingw-w64-x86_64-windows-default-manifest 6.4-4
mingw-w64-x86_64-winpthreads-git 10.0.0.r113.g57fd0b77a-1
mingw-w64-x86_64-xz 5.2.7-1
mingw-w64-x86_64-zlib 1.2.13-1
mingw-w64-x86_64-zstd 1.5.2-2
```

Any help appreciated

**Comment by flossy83** [comment]
Oh I tried putting `#include <memory>` in info.h and info.cpp like the compiler error suggested and it works now, I get a TIVTC.dll file.

But, it doesn't work:

![Untitled-1](https://github.com/pinterf/TIVTC/assets/46382337/a369410e-5321-49d7-a361-dd805679274a)

I guess it must have built wrongly -  [here](https://drive.google.com/file/d/1HGr3ZnML4Nq03bLokrulqrI_7Icq386h/view?usp=sharing) is the actual file.

It looks like it the first make command autodetected my CPU as AMD - "-- Detected target processor as: AMD64".  Is that correct?  My CPU is Intel i5-4570.   Are there some make commands I can add to tell it to try building a different version?

**Comment by flossy83** [comment]
If I move the TIVTC.dll to another location, eg. C:\ and do a LoadPlugin("C:\TIVTC.dll") then I get a meaningful error message code 126:

![debug avs_snapshot_00 01 356](https://github.com/pinterf/TIVTC/assets/46382337/65d3a601-21eb-4b22-9c5a-83758be7333d)

I don't know why it shows it as forward slash, it's definitely a backslash in my script

**Comment by flossy83** [comment]
Seems to be missing some libgcc dependencies...

![Untitled-1 copy](https://github.com/pinterf/TIVTC/assets/46382337/d24d6a48-e1a2-402c-b586-d6ca5b0f87bd)

**Comment by flossy83** [comment]
I think I need to tell GCC to include those dependencies in the compilation, but I don't know how

**Comment by flossy83** [comment]
According to a StackOverflow post I need to compile with flags:  -static-libstdc++ -static-libgcc 

But I'm not sure how to do that -- do I need to modify the makefiles?

**Comment by flossy83** [comment]
Tried putting `set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")`  inside all CMakeLists.txt files to no effect

**Comment by pinterf** [comment]
Are you using mingw built Avisynth+? Mingw and Windows-style DLLs are not ABI compatible. Plugin using C interface has no problems, but they are very rare. The real expert of MSys2/Mingw64 is @qyot27, I'd ask him.

**Comment by flossy83** [comment]
> Are you using mingw built Avisynth+? 

I'm using the current latest public release from the GitHub repository, so I guess that means no.

I managed to include all those GCC dependencies in TIVTC.dll by putting `set(CMAKE_CXX_FLAGS "-static")` inside all CMakeLists.txt files  - in this case Avisynth Info Tool reports no problems with the .dll but I still get the "no function named TDecimate" when trying to call TDecimate().

But LoadPlugin("C:\TIVTC.dll") doesn't throw an error anymore, and the TIVTC.dll is bigger so I know it included those GCC dependencies.

So I guess the MinGW builds just aren't compatible with the public release build of Avisynth+, so I probably have to use Visual Studio to compile it instead, have I got that right?

**Comment by pinterf** [comment]
Yes, mingw built C++ plugins are compatible only with mingw build Avisynth+.
(following the README.md build instructions I've encountered the missing header, so I fixed it).
As for Visual Studio: open the solution file (.sln) in the IDE and build the project. I usually do this.

**Comment by pinterf** [comment]
(As for mingw built DLL / Load error 126: The missing DLLs (standard c++ library, posix threads, library (but I don't think TIVTC is using that) are somewhere in your gcc directory. The command ``ldd <your_dll_name>`` can list the dependencies if they are not statically linked (as you finally did).

**Comment by qyot27** [comment]
> It looks like the first make command autodetected my CPU as AMD - "-- Detected target processor as: AMD64". Is that correct? My CPU is Intel i5-4570. Are there some makefile switches I can set to tell it to try building a different version?

[`amd64` is just the architecture name used by some distros and projects, because AMD was the one that actually extended x86 into x86_64.](https://en.wikipedia.org/wiki/X86-64#Industry_naming_conventions)

Using VS through the command-line CMake interface can be done by first launching the Visual Studio Command Prompt and specifying "Visual Studio XX 20YY" as the generator, where the XX and YY refer to whatever version of VS is being used (16 2019, for example).

Overriding/appending CMAKE_CXX_FLAGS or CMAKE_SHARED_LINKER_FLAGS doesn't usually involve needing to edit CMakeLists.txt, as virtually every sort of thing you can `set()` inside of them can also be passed to the CLI at configure time, e.g. `-DCMAKE_CXX_FLAGS="-static"` or `-DCMAKE_SHARED_LINKER_FLAGS="-static-libgcc"`.

But yes, as stated, GCC and MSVC use incompatible C++ ABIs and you can't mix and match host and plugins across compilers.  And by default, GCC-built AviSynth+ actually looks in a completely different set of directories for plugins (plugins_gcc and plugins64_gcc), so as not to cause load errors.

**Comment by flossy83** [comment]
Thanks, a bit disappointing as I was trying to avoid using the Visual Studio GUI .    I tried the 2019 Community version and it's ok but it only lets me compile the CLang version due to missing compilation tools.   Guess I need the 2022 version?

**Comment by pinterf** [comment]
The solution and project files are set to v143 platform toolset, this is what vs2022 uses. For vs2019 go into config and change that to v142 toolset, that must be fine.
