### ISSUE TITLE
Pull request - add frame property "TDecimateCycleMetrics"

### ISSUE THREAD

**Issue by flossy83** [pinterf/TIVTC#48]
Not sure if you're getting notifications for pull requests so I'll chuck this here as well  https://github.com/pinterf/TIVTC/pull/47

**Comment by pinterf** [comment]
Thanks, integrated your last doc change, a bit reorganized (btw, your text editor inserted TABs in the txt file, which I replaced with spaces), and made a release. For additionial changed, we need to open a new issue.
