### ISSUE TITLE
Vapoursynth support?

### ISSUE THREAD

**Issue by Selur** [pinterf/TIVTC#49]
Since https://github.com/dubhater/vapoursynth-tivtc really does not seem to get updated, it would be nice if you could adjust TIVTC to also be compatible with Vapoursynth. :)

**Comment by pinterf** [comment]
I don't like working twice. VS has a proper port and has indeed a bit more features than Avisynth  Tivtc (frame property setting for vfr clips, etc).

**Comment by Selur** [comment]
Unterstood, thanks.
