### ISSUE TITLE
something is wrong with slow=2 mode

### ISSUE THREAD

**Issue by 299792458m** [pinterf/TIVTC#5]
I used tritical's TIVTC(1.05) with slow=2 option, and the result is diffrent from yours.
and I noticed that in TFM.cpp, compareFieldsSlow2 with field!=0 section something is wrong.
(just compared with asm block.)
--arround  line 1720 the address of nxtnnf and prvnnf does not updated.
--at line 1685, may "(eax & 7)" instead of "56"?
--at line 1708, may "(diff_n_c > 42)" instead of "2" ?
--at line 1709, may "(eax & 2)" instead of "16"?

**Comment by 299792458m** [comment]
I hope my wasted time helps you.
reverse engineering from assembly with little comments make us crazy...

**Comment by pinterf** [comment]
Right. As a blind test, I've checked it independently and found the same differences.

**Comment by 299792458m** [comment]
thanks for new release.
but, still "nxtnnf" not updated. is it? (or need not....?)

**Comment by pinterf** [comment]
Thx, needed. Check v1.0.14 pls.

**Comment by 299792458m** [comment]
thanks! the result was matched with 1.05.
