### ISSUE TITLE
TIVTC v1.0.15 AnimeIVTC error

### ISSUE THREAD

**Issue by JySzE** [pinterf/TIVTC#8]
AnimeIVTC is not working now after most recent TIVTC  update: 

Im getting errors "TFMPP: clip2 colorspace must be the same as input clip!"

![image](https://user-images.githubusercontent.com/25883052/81494698-bede2780-925f-11ea-9087-ccae0df850cd.png)

TIVTC v1.0.14 (20190207) and TDeint v1.3 (20200508) works fine.

**Comment by pinterf** [comment]
Thanks, others reported as well, fix is coming soon.

**Comment by pinterf** [comment]
Fixed in 1.0.16

**Comment by JySzE** [comment]
Awesome, confirmed that it works now on my end. Thank you.

**Comment by JySzE** [comment]
Getting another error: 

![Screenshot_1](https://user-images.githubusercontent.com/25883052/81664960-f3371c80-93f4-11ea-8ab4-447b034fd5da.png)

Reverted back to 1.0.14 and all was fine.

This error occured after creating the tfm and stats with an analysis pass, it ended up with a larger stats file.

stats.txt (1.0.14) = 51kb - works fine.

stats.txt (1.0.16)= 87kb - error

Here is what I used to generate the txt files:

```
MPEG2Source("MPG\OP1\OP1.d2v")

AnimeIVTC(mode=4,precision=4,omode=2,pass=1,MI=100)
```

After closing and opening avpsmod again i changed it to pass=2 and reloaded and that's when i was greeted with that error above.

Debug file comes out with this: 

`passThrough=1 cycle=5 nfrms=2732 vidThresh=1.100000 np=3`

**Comment by pinterf** [comment]
Maybe it's source dependent, could not reproduce. v16 and v14 generates the very same txt and results for me. Could you create and provice a short video sequence that still crashes for you?

**Comment by JySzE** [comment]
https://www.mediafire.com/file/yo9mklf8aljjbxu/TVITC_Error_example.zip/file

**Comment by pinterf** [comment]
Thanks, it helped much, check please v1.0.17

**Comment by JySzE** [comment]
Works, I appreciate the hard work and speedy fix.
