### ISSUE TITLE
TIVTC 1.0.16 error

### ISSUE THREAD

**Issue by User9013** [pinterf/TIVTC#9]
At 1.0.16, I get a new error.

![エラー](https://user-images.githubusercontent.com/65251154/81734722-ebe44180-94ce-11ea-925f-e52668cc3dd3.png)

This error was caused by using the following function.

---------------------------------------------------------------------------------------
function Film24P(clip clip){
sclip=clip.nnedi3(field=1)
Interp=clip.AssumeTFF().eedi3(field=1,sclip=sclip)
m1=clip.TMM2(mtype=2,ttype=5)
Deinted=clip.TDeint(order=1,field=1,edeint=Interp,emask=m1,slow=2)
clip=clip.TFM(mode=6,order=1,PP=7,slow=2,mChroma=true,clip2=Deinted)
clip=clip.crop(0,110,0,-306).TDecimate(mode=1,clip2=clip)
return clip
}
---------------------------------------------------------------------------------------

Reverted back to 1.0.14 and all was fine.

**Comment by pinterf** [comment]
Thanks for the report. Could you please check v1.0.17

**Comment by User9013** [comment]
I've tried 1.0.17, no problem.
Thank you very much.
